swagger: '2.0'

schemes: # é uma definição dos protocolos que serão aceitos pela api
  - http
  - https

host: localhost:8085 # esta porta é apenas um exemplo - a 8080 foi evitada no curso para evitar conflitos
basePath: /bytebank-api/v1

info: # O info são metadados como título e descrição sobre a sua api.
  version: 1.0.0
  title: ByteBank API
  description: Administração da movimentação bancária e controle de acesso através de senha e cpf.
  termsOfService: http://localhost:8085/bytebank-api/v1/termo-uso # endereço de acesso à documentação da api
  contact: #São dados de contato para o suporte da manutenção da api
    name: Suporte
    url:  http://localhost:8085/bytebank-api/v1/suporte
    email: suporte@bytebankapi.com
  license: # Não é obrigatório.
    name: MIT
    url: http://opensource.org/licenses/MIT

paths:
  '/cliente':
    post:
      summary: Cadastra cliente
      description: Cadastra um novo cliente
      operationId: cadastraCliente # aqui você especifica o nome do método no java
      parameters:
        - in: body # significa que os parâmetros estão no corpo da requisição
          name: cliente_ # quando você colocar um parâmetro de nome igual ao path, adicione um _ no final para evitar um erro.
          schema: # o schema é a definição de tipo e atributos do parâmetro.

      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: Cadastro efetuado com sucesso
          schema:
            type: object
            properties:
              titular:
                type: string
                example: Janete
        400:
          description: Requisição inválida
        500:
          description: Erro interno no servidor

definitions:

  Cliente:
    type: object
      properties:
        id:
          type: integer
          format: int64 # Converte ele para um Long
          example: 234
        titular:
          type: string
          example: Janete # esse atributo é apenas um exemplo que você poderá ver no editor online do swagger. Não afeta a api em si.
        cpf:
          type: string
          maxLength: 11
          minLength: 11
          example: 01234567890
        senha:
          type: string
          format: password
          example: senha123
        conta:
          type: array
          items:
            $ref: '#/definitions/Conta'
