apiVersion: v1
kind: Service
metadata:
  name: service-aplicacao
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: aplicacao-pod # irá trabalhar com todos os pods com o nome de aplicacao-pod.
