version: "3.0"
services:
  db: # Isto aqui é apenas um nome que você dá para o serviço/container, poderia ser qualquer coisa.
    image: mysql:5.7.19
    environment:
      - MYSQL_DATABASE=loja
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - C:\Dev\Projetos\CursosAlura\Infraestrutura\EntregaContinua\06KubernetsIntroducaoAOrquestracaoDeContainers\volume_mysql:/var/lib/mysql
  web:
    image: rafanercessian/aplicacao-loja:v1
    ports:
      - 8080:80
    depends_on:
      - db
